export default {
	appName:"Smsari",
	login:"S'identifier",
	sign_up:"s'inscrire",
	email_not_valid:"Veuillez saisir une adresse e-mail valide.",
	password_less_char:"Veuillez entrer au moins 8 caractères",
	confirm_password:"Confirmez le mot de passe",
	same_password:"Veuillez entrer le même mot de passe",
	forgot_password: "mot de passe oublié ?",
	nom: "Nom Complete",
	nom_placeholder: "Nom Complete",
	nom_not_valid: 'Entrez un nom valide',
	email:'Email',
	email_placeholder:'email@exemple.com',
	phone: 'phone ',
	phone_not_valid:'Entrez un numéro de téléphone valide',
	phone_placeholder: 'Numéro de téléphone',
	age:'Age',
	age_placeholder:'34',
	sexe: 'Sexe',
	gender_m:'Homme',
	gender_f:'Femme',
	project:'Project',
	title_projectList:'List des projets',
	title_projectDetail:'Détail de projet',
	title_declareClient:'Déclare un client',
	title_monespace:'Mon espace',
	title_logOut:'logOut',
	titleAuth:'Authentication',
	signOut:'Déconnexion',
	alert:{
		user_create:'Utilisateur créé avec succès',
		user_update:'Utilisateur modifier avec succès',
		unable_user_create:'Unable to create user',
		unable_user_update:'Unable to update user',
		declared_title:'Déclare Client',
		declared_successfully:'Le client a été déclaré avec succès',
		declared_fail:'Unable to declare client',
	}
}